server:
  port: 8500

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
#    healthcheck:
#      enabled: true

management:
  security:
    enabled: false
