spring:
  application:
    name: product-client

  rabbitmq:
    host: 10.202.161.200
    port: 5672
    username: bluser
    password: bluser

server:
  port: 9705

eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 2000