server:
  port: 9501

spring:
  application:
    name: hystrix-turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/


  instance:
    prefer-ip-address: true
turbine:
  app-config: product-ui
  cluster-name-expression: "'default'"


